### ISSUE TITLE
cuda 12.1

### ISSUE THREAD

**Issue by ehartford** [s4rduk4r/alpaca_lora_4bit_readme#1]
I have cuda 12.1
is it necessary for me to install cuda 11.7?

**Comment by s4rduk4r** [comment]
If you're using WSL, then only CUDA WSL Ubuntu has to be 11.7. In Linux environment, I guess you'll have to stick with 11.7 so far, because [GPTQ-for-LLaMa](https://github.com/qwopqwop200/GPTQ-for-LLaMa) setup_cuda.py expects exactly that version. Even 11.8 won't do at the moment

**Comment by ehartford** [comment]
> /etc/ld.so.conf.d/cuda-11-7.conf to add at the end of the file additional line /usr/local/cuda-11.7/lib64 Thankfully these changes seems to be permanent

When I ls that directory, I don't see a "cuda-11-7.conf"

I only see

```
000_cuda.conf                   gds-12-1.conf
988_cuda-12.conf                ld.wsl.conf
989_cuda-11.conf                libc.conf
fakeroot-x86_64-linux-gnu.conf  x86_64-linux-gnu.conf
gds-11-7.conf
```

Should I edit 989_cuda-11.conf instead?

**Comment by ehartford** [comment]
https://github.com/s4rduk4r/alpaca_lora_4bit_readme#5-get-lora

I only do this if I'm not fine-tuning the lora weights myself, right?

**Comment by ehartford** [comment]
the line:

```
wget https://huggingface.co/decapoda-research/llama-13b-hf-int4/resolve/main/llama-13b-4bit.pt ../llama-13b-4bit.pt
```

Can I generate my own 4-bit quantized model from the llama model, instead of downloading it?  (because I want to use 30b and that model doesn't exist in hf/decapoda-research)

edit: never mind I found a 30b model here:
https://huggingface.co/maderix/llama-65b-4bit/blob/main/llama30b-4bit.pt

**Comment by s4rduk4r** [comment]
Glad you've managed to figure everything out
