### ISSUE TITLE
get model step

### ISSUE THREAD

**Issue by ehartford** [s4rduk4r/alpaca_lora_4bit_readme#5]
I am trying to do the get model step

https://github.com/s4rduk4r/alpaca_lora_4bit_readme#4-get-model

and it says download a .pt file.

But the model I want to use, it's llama-30b-4bit-128g.safetensors
How do I need to change your procedure in order to use llama-30b-4bit-128g.safetensors instead of a .pt?

**Comment by s4rduk4r** [comment]
For `.safetensors` files its all the same. Just be sure to provide the paths to the model and its configuration folder via `--llama_q4_model` and `--llama_q4_config_dir` command line arguments

**Comment by ehartford** [comment]
Thanks, I figured it out :D
